# Generated by Django 5.2.13 on 2026-04-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_no',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
