# Generated by Django 5.2.13 on 2026-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('call', 'Call'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('walkin', 'Walk-In'), ('referral', 'Referral')], max_length=100),
        ),
    ]
