# Generated by Django 5.2.13 on 2026-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_email_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=100),
        ),
    ]
