# Generated by Django 5.2.13 on 2026-04-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow_up',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='follow_up',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.CreateModel(
            name='LeadCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=10, unique=True)),
                ('lead_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_no', models.CharField(max_length=12, unique=True)),
                ('course_interested', models.CharField(max_length=100)),
                ('lead_source', models.CharField(choices=[('walk_in', 'Walk-in'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('phone_enquiry', 'Phone Enquiry'), ('website', 'Website')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_notes', models.TextField(blank=True, null=True)),
                ('enquiry_date', models.DateField()),
                ('next_followup_date', models.DateField()),
                ('initial_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('demo_scheduled', 'Deme Scheduled'), ('enrolled', 'Enrolled'), ('lost', 'Lost')], default='new', max_length=20)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
        migrations.DeleteModel(
            name='Follow_up',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
