# Generated by Django 5.2.13 on 2026-04-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_follow_up_created_by_remove_follow_up_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(blank=True, max_length=100, null=True)),
                ('call_date', models.DateField(blank=True, max_length=100, null=True)),
                ('call_time', models.TimeField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('call_outcome', models.CharField(choices=[('Interested', 'Interested'), ('Not Reachable', 'Not Reachable'), ('Demo Scheduled', 'Demo Scheduled'), ('Not Interested', 'Not Interested')], max_length=50)),
                ('notes', models.TextField()),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
