# Generated by Django 5.2.13 on 2026-05-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_calllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcapture',
            name='course_interested',
            field=models.CharField(choices=[('fullstack', 'Full Stack Development'), ('frontend', 'Front-End Development'), ('backend', 'Back-End Development'), ('python', 'Python Programming'), ('java', 'Java Programming'), ('dotnet', '.NET Development'), ('mern', 'MERN Stack Development'), ('mean', 'MEAN Stack Development'), ('data_science', 'Data Science'), ('ai_ml', 'AI & Machine Learning'), ('cyber_security', 'Cyber Security'), ('cloud_computing', 'Cloud Computing'), ('uiux', 'UI/UX Design')], max_length=100),
        ),
        migrations.AlterField(
            model_name='leadcapture',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
