# Generated by Django 5.2.13 on 2026-05-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_leadcapture_course_interested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcapture',
            name='initial_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('demo_scheduled', 'Deme_Scheduled'), ('enrolled', 'Enrolled'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
