# Generated by Django 5.2.13 on 2026-05-25 12:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(choices=[('sales', 'Sales'), ('telecall', 'Telecall'), ('support', 'Support'), ('trainers', 'Trainers'), ('hr', 'HR'), ('management', 'Management')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('sales_executive', 'Sales Executive'), ('telecaller', 'Telecaller'), ('support', 'Support Staff'), ('hr', 'HR'), ('trainer', 'Trainer')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_manage_leads', models.BooleanField(default=False)),
                ('can_manage_staff', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_mark_attendance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Staff Roles',
                'db_table': 'staff roles',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('monthly_target', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('performance_rating', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=20)),
                ('date_of_joining', models.DateField()),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='staff.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='staff.staffrole')),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee_id'], name='staff_employe_f9cdad_idx'), models.Index(fields=['email'], name='staff_email_090e5f_idx'), models.Index(fields=['status'], name='staff_status_c91b08_idx'), models.Index(fields=['department'], name='staff_departm_a70fd6_idx')],
            },
        ),
    ]
