# Generated by Django 5.2.13 on 2026-05-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffrole',
            table='staff_roles',
        ),
    ]
