# Generated by Django 5.2.13 on 2026-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffrole_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
