# Generated by Django 5.2.13 on 2026-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='staff/documents/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/'),
        ),
    ]
