# Generated by Django 5.2.13 on 2026-06-03 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_documents_staff_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='performance_rating',
            field=models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
