# Generated by Django 5.2.13 on 2026-06-08 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_staff_performance_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('class', 'Class'), ('meeting', 'Meeting')], max_length=20)),
                ('topic', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.staff')),
            ],
            options={
                'db_table': 'trainer_schedule',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
